.TH SKRYPT 1 "29 April 2025" "Version 0.1" "System Info Script Manual"
.SH NAME
main \- Skrypt do wyświetlania i zapisywania informacji o systemie
.SH SYNOPSIS
.B ./main.sh
.RI [ opcje ]
.SH DESCRIPTION
Skrypt wyświetla szczegółowe informacje o systemie, takie jak dane o procesorze, pamięci RAM, dyskach, czasie działania systemu i sieci. Umożliwia również zapis raportów do pliku.

.SH OPCJE
.TP
.B -h
Wyświetla pomoc.
.TP
.B -v
Wyświetla informacje o wersji i autorze.
.TP
.B man
Wyświetla stronę manuala.

.SH PRZYKŁADY
Uruchomienie skryptu:
.B ./main.sh

Wyświetlenie pomocy:
.B ./main.sh -h

Wyświetlenie informacji o wersji:
.B ./main.sh -v

.SH AUTOR
Filip Grela (fgrela09@gmail.com)